### PR TITLE
Protomech record sheet overhaul

### LINKED ISSUE #253: Quad Protomech Armor Diagram
### Environment
0.45.3
Platform Windows 7 6.1 (x86)
Java version 1.8.0_151

### Description
When printing quad protomechs, the armor diagram remains bipedal and armor for the legs becomes incorrect.

### Files
boggart quad

### PR DESCRIPTION
**Pull request by neoancient**
I think this is step 4c. Besides overhauling the printing of standard-weight bipeds, this also adds the ability to print ultraheavies as well as quads and gliders.

Here is the sample:
[protomechs.pdf](https://github.com/MegaMek/megameklab/files/4653174/protomechs.pdf)

Closes #253

### CODE REVIEW

File: src/megameklab/com/printing/PrintProtomech.java [hunk 1]
```diff
@@ -0,0 +1,188 @@
...
+            setTextField(MP_JUMP, getEntity().getAllUMUCount());
+        }
+        printTorsoCritChart();
+        if (!proto.hasMainGun()) {
+            hideElement(MAIN_GUN_ARMOR);
+            hideElement(MAIN_GUN_SHADOW);
+            hideElement(MAIN_GUN_TEXT);
+        }
+        if (proto.hasUMU()) {
+            setTextField(LBL_JUMP, "Underwater");
```
Comment (NickAragua) [inline src/megameklab/com/printing/PrintProtomech.java:100]: This seems redundant and/or replaces what's on line 90.

Comment (neoancient) [reply src/megameklab/com/printing/PrintProtomech.java:100]: I must have written them on different days.
