### PR TITLE
Military toggle update

### LINKED ISSUE #670: Changing DropShip engine from military to civilian does not update displayed information
Using MML 0.47.7 on OS X with Java build 1.8.0_51-b16, if I toggle the Military checkbox, the displayed Burn Days 1G for fuel usage does not change. Neither do the number of free heat sinks or the available Tonnage at the bottom of the window do not update. If this either makes the design overweight or under-sinked, MML does not immediately mark it as invalid.

However, if you try to save the unit, MML _will_ issue a warning about saving an invalid unit, so somewhere it does check the free heat sinks.

To reproduce:
1. Load the standard Mule (2737), which for some reason has a military-grade engine. (Is that a bug?) It gets 121 heat sinks free, and has 121 heat sinks total. Its Burn Days 1G is 173.37, which is correct for a military engine.
2. Uncheck the Military box. Nothing else changes on the screen. Burn Days 1G is still 173.37, there are still 121 free heat sinks, and the mass is still 11,200/11,200.
3. Save the unit. The "Warning: Invalid unit, may save incorrectly!" message appears. The unit will be saved to data/mechfiles/ without prompting you for a location. (I thought this was fixed in an earlier version?)
4. Validate the unit. The Mule is listed as 11262.0 tons, with the excess 62 being heat sinks. The Tonnage displayed at the bottom of the screen remains 11,200, and the red invalid flag at the bottom is still not there.
5. Add and remove half a ton of fuel. Burn Days 1G correctly updates, as does the Tonnage displayed at the bottom. The unit is now clearly marked invalid.
6. Reload the Mule from the cache and again uncheck the Military box.
7. Remove one heat sink. The displayed number of weight-free heat sinks is still listed as 121, although the tonnage at the bottom now correctly indicates the design is 61 tons over and the invalid flag is visible.
8. Reduce the speed to 2 and return it to 3. Now the number of weight-free heat sinks is correctly listed as 59.

### PR DESCRIPTION
**Pull request by neoancient**
Added code to update the heat, fuel, and summary panels and the status bar when the military/civilian checkbox is toggled.

Fixes #670

### CODE REVIEW

File: src/megameklab/com/ui/aerospace/AdvancedAeroStructureTab.java [hunk 1]
```diff
@@ -175,23 +174,6 @@ public void refresh() {
...
-                    continue;
-                }
-
-                if (cs.getIndex() == systemType) {
-                    getJumpship().setCritical(loc, slot, null);
-                }
-            }
-        }
-    }
-
```
Comment (neoancient) [inline src/megameklab/com/ui/aerospace/AdvancedAeroStructureTab.java:194]: This method is a vestige of copying and pasting the mech structure tab as a starting point. It's not used for aerospace units (same with DS/SC below).
