### PR TITLE
Industrial tripod cockpit

### LINKED ISSUE #1315: Superheavy industrial tripod fire control
MML HQ Lab 49.14

Win 11

Description
Superheavy industrial tripod does not have the option for advanced fire control.

### LINKED ISSUE #1371: Incorrect cockpit weights for tripod industrialmeks
### Environment
MekLab 49.17 from MekHQ
Linux
OpenJDK 17.09

### Description
The default Industrial Cockpit for a mek that is Industrial and a Tripod weighs three tons, as shown in the Unit Weight Breakdown:

> `Industrial Cockpit:                                              3.0`

This holds whether the mek is superheavy or not.

Per IO:AE p159, tripod cockpits should always weigh either 4 tons for standard weights or 5 tons for superheavies, regardless of if the mek is industrial. 

Related: issue #1315.

### PR DESCRIPTION
**Pull request by neoancient**
Makes a distinction between tripod industrial mechs with and without active fire control. Also fixes a couple of bugs I noticed during testing, involving cockpit type not updating when switching an industrial mech to tripod or switching between standard weight and superheavy.

Requires Megamek/megamek#5291.

Fixes #1315
Fixes #1371

### CODE REVIEW

File: megameklab/src/megameklab/ui/mek/BMMainUI.java [hunk 1]
```diff
@@ -137,8 +137,6 @@ public void createNewUnit(long entityType, boolean isPrimitive, boolean isIndust
         mech.addEngineCrits();
         if (isPrimitive) {
             mech.addPrimitiveCockpit();
-        } else if (isIndustrial) {
```
Comment (neoancient) [inline megameklab/src/megameklab/ui/mek/BMMainUI.java:140]: I removed this branch because it is already handled in Mech::addCockpit in the else branch below.

File: megameklab/src/megameklab/printing/reference/GroundToHitMods.java [hunk 2]
```diff
@@ -64,9 +64,7 @@ private void addMekAttackerMods() {
         addRow("", bundle.getString("skidding"), "+1");
         if (((Mech) entity).getCockpitType() == Mech.COCKPIT_PRIMITIVE_INDUSTRIAL) {
             addRow("", bundle.getString("noFireCon"), "+2");
-        } else if ((((Mech) entity).getCockpitType() == Mech.COCKPIT_PRIMITIVE)
-                || (((Mech) entity).getCockpitType() == Mech.COCKPIT_INDUSTRIAL)
-                || (((Mech) entity).getCockpitType() == Mech.COCKPIT_SUPERHEAVY_INDUSTRIAL)) {
+        } else if (((Mech) entity).hasAdvancedFireControl()) {
```
Comment (pavelbraginskiy) [inline megameklab/src/megameklab/printing/reference/GroundToHitMods.java:67]: I think this should be negated, `!((Mech) entity).hasAdvancedFireControl()`

**Review by pavelbraginskiy — APPROVED** [review]
