### PR TITLE
Skip weapon groups and fixed location equipment when resetting crits

### LINKED ISSUE #461: Removed items of Aerospace Fighter are still on the equipment list.
### Environment
Ver 0.47.4

### Description
If you remove the items on the already assigned canon Aerospace Fighter unit, then move to the Assign Criticals section and press Reset, these removed weapons are shown on the lists - but even if you drag the ghost items to the parts nothing happens.

### PR DESCRIPTION
**Pull request by neoancient**
The reset button on the aerospace fighter build tab is removing all equipment, including squadron weapon groups, which creates phantom weapons that can't be reinstalled. Equipment with a fixed location, such as ammo, should also not be removed when resetting.

This file was apparently CR/LF before.

Fixes #461

### CODE REVIEW

File: src/megameklab/com/ui/Aero/tabs/BuildTab.java [hunk 1]
```diff
@@ -1,136 +1,138 @@
...
+        if (e.getActionCommand().equals(RESETCOMMAND)) {
+            resetCrits();
+        }
+    }
+
+
+    private void resetCrits() {
+        for (Mounted mount : getAero().getEquipment()) {
+            if (!mount.isWeaponGroup() && TestAero.eqRequiresLocation(mount.getType(), true)
+                    && !UnitUtil.isFixedLocationSpreadEquipment(mount.getType())) {
```
Comment (Windchild292) [inline src/megameklab/com/ui/Aero/tabs/BuildTab.java]: All changes are on these two lines
