### PR TITLE
Large craft auto-allocate

### LINKED ISSUE #267: Dropship armor values calculating and auto-allocating incorrectly
### Environment
MML 45.3 dev standalone (downloaded with MHQ)

Windows 10, Java 8

### Description
Create a new dropship, click Maximize Armor followed by Auto-Allocate Armor
The result is this; 

image

Wasted and negative unallocated armor points at the same time. 
Dropship armor points are never wasted, as dropship armor is limited by tonnage not by points. 
Auto-allocating armor should not allocate more armor than is available.

At a guess, dropship bonus armor might be the cause. 

MMLLog contains nothing noteworthy, I can attach if you want.

### LINKED ISSUE #276: Auto allocate skips advanced aerospace side rear locations.
Based on this forum thread.

https://bg.battletech.com/forums/index.php?topic=64700.0

Looks like the aft sides are defaulting or allocating 10 points.

### PR DESCRIPTION
**Pull request by neoancient**
Fixes three closely-related issues:
1. Dropships and small craft get bonus armor from their SI to each location. This was including the non-armored system-wide location.
2. The above units as well as advanced aerospace units were having the number of bonus armor points added in twice when apportioning armor points using auto-allocate.
3. The auto-allocate code for JS/WS/SS was copied from SC/DS without being modified for the two extra armor locations, so side rear locations were not getting any armor beyond the bonus from SI.

Bonus issue, previously unreported: added logic to make sure that auto-allocate does not assign any values less than the minimum, which is the bonus provided by SI.

Fixes #267 
Fixes #276

### CODE REVIEW

File: src/megameklab/com/ui/aerospace/AdvancedAeroStructureTab.java [hunk 1]
```diff
@@ -517,35 +517,47 @@ public void armorPointsChanged(int location, int front, int rear) {
 
     @Override
     public void autoAllocateArmor() {
-        for (int loc = 0; loc < getJumpship().locations(); loc++) {
+        for (int loc = 0; loc < getJumpship().locations() - 1; loc++) {
```
Comment (VicenteCartas) [inline src/megameklab/com/ui/aerospace/AdvancedAeroStructureTab.java]: Would be nice to add a comment that the last location is not a valid location?

File: src/megameklab/com/ui/aerospace/AdvancedAeroStructureTab.java [hunk 2]
```diff
@@ -517,35 +517,47 @@ public void armorPointsChanged(int location, int front, int rear) {
...
             getJumpship().initializeArmor(0, loc);
         }
         
-        // divide armor among positions, with more toward the front
+        // divide armor (in excess of bonus from SI) among positions, with more toward the front
+        int bonusPerFacing = (int) Math.floor(UnitUtil.getSIBonusArmorPoints(getJumpship()) / 6.0);
```
Comment (VicenteCartas) [inline src/megameklab/com/ui/aerospace/AdvancedAeroStructureTab.java]: Is that 6 a constant/value we could get from somewhere instead of hardcode it here?

File: src/megameklab/com/ui/aerospace/DropshipStructureTab.java [hunk 3]
```diff
@@ -1,591 +1,592 @@
...
+
+    @Override
+    public void escapeChanged(int lifeBoats, int escapePods) {
+        getSmallCraft().setLifeBoats(lifeBoats);
+        getSmallCraft().setEscapePods(escapePods);
+        refreshSummary();
+        refresh.refreshStatus();
+        refresh.refreshPreview();
+    }
+
```
Comment (VicenteCartas) [inline src/megameklab/com/ui/aerospace/DropshipStructureTab.java]: nit: extra white lines. The only change here is line endings?

File: src/megameklab/com/ui/aerospace/AdvancedAeroStructureTab.java [hunk 4]
```diff
@@ -517,35 +517,48 @@ public void armorPointsChanged(int location, int front, int rear) {
...
-        // divide armor among positions, with more toward the front
+        // divide armor (in excess of bonus from SI) among positions, with more toward the front
+        int bonusPerFacing = (int) Math.floor(UnitUtil.getSIBonusArmorPoints(getJumpship()) / ARMOR_FACINGS);
         int points = UnitUtil.getArmorPoints(getJumpship(), getJumpship().getLabArmorTonnage())
-                + getAero().getSI() * getAero().locations();
-        int nose = (int)Math.floor(points * 0.3);
-        int wing = (int)Math.floor(points * 0.25);
-        int aft = (int)Math.floor(points * 0.2);
-        int remainder = points - nose - wing - wing - aft;
+                - bonusPerFacing * 6;
```
Comment (VicenteCartas) [inline src/megameklab/com/ui/aerospace/AdvancedAeroStructureTab.java]: Can use constant here

File: src/megameklab/com/ui/aerospace/AdvancedAeroStructureTab.java [hunk 5]
```diff
@@ -517,35 +517,48 @@ public void armorPointsChanged(int location, int front, int rear) {
...
+        int nose = (int)Math.floor(points * 0.22);
+        int foresides = (int)Math.floor(points * 0.18);
+        int aftsides = (int) Math.floor(points * 0.16);
+        int aft = (int)Math.floor(points * 0.10);
+        int remainder = points - nose - foresides * 2 - aftsides * 2 - aft;
         
-        // spread remainder among nose and wings
-        switch(remainder % 4) {
+        // spread remainder among nose and fore sides
+        switch(remainder % 6) {
```
Comment (VicenteCartas) [inline src/megameklab/com/ui/aerospace/AdvancedAeroStructureTab.java]: Can use constant here
